name: Verde
favicon: null
layout_spectrum: 0.54485
typography_spectrum: 0.8142223642207682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c4b50'
    - '#a3a1a6'
    - '#00a949'
    - '#53b385'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.435592696769163
  rhythmicContrast: 0.5
purpose: []
